version: "2"

services:
  dukecon-httpd-base:
    image: dukecon/dukecon-httpd-base:latest
    build:
      context: httpd-base
  dukecon-httpd-edge:
    image: dukecon/dukecon-httpd-edge:latest
    build:
      context: httpd-edge
  dukecon-httpd-edge-with-static:
    image: dukecon/dukecon-httpd-edge-with-static:latest
    build:
      context: httpd-edge-with-static
  dukecon-maven:
    image: dukecon/dukecon-maven:latest
    build:
      context: maven
  dukecon-node:
    image: dukecon/dukecon-node:latest
    build:
      context: node
